#!/usr/bin/env python3
"""Build the CORAfrica static site into site/.

Content lives here; the chrome (head, header, footer) is defined once and
shared, so a nav or footer change is a one-line edit rather than nine.
Generated files carry a do-not-edit banner.

    python3 build.py

Every fact is sourced from docs/CONTENT-FACTS.md. Placeholders awaiting
Fr. Peter are written in [SQUARE BRACKETS] so they cannot ship unnoticed.
"""
import hashlib
import os
import re

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "site")


def assetv(name):
    """Content hash for cache-busting. GitHub Pages serves CSS with max-age=600,
    so without this a style change is invisible for ten minutes."""
    p = os.path.join(OUT, name)
    if not os.path.exists(p):
        return name
    h = hashlib.md5(open(p, "rb").read()).hexdigest()[:8]
    return "%s?v=%s" % (name, h)
BASE = "https://corafrica.org.ng"

# Verified live 2026-09-01 by opening each link. BOTH are recurring
# subscriptions at a fixed amount; there is currently NO one-time link.
# The full monthly ladder, recovered from the live donate page's markup and each
# one opened to confirm the amount matches the label.
STRIPE_MONTHLY = [
    ("10",    "https://donate.stripe.com/eVq14p1O83Q66iT71Wcwg00"),
    ("25",    "https://donate.stripe.com/7sYdRbeAUcmCgXx3PKcwg01"),
    ("50",    "https://donate.stripe.com/dRmbJ39gA86m22D0Dycwg02"),
    ("100",   "https://donate.stripe.com/8x29AV9gAbiy5eP71Wcwg03"),
    ("250",   "https://donate.stripe.com/fZu4gB1O8dqG22DgCwcwg04"),
    ("500",   "https://donate.stripe.com/7sY14pakE4Ua4aLbiccwg05"),
    ("1,000", "https://donate.stripe.com/8x26oJfEY72i36Hcmgcwg06"),
]
STRIPE_25_MONTHLY = STRIPE_MONTHLY[1][1]

# One-time giving on the old site is a GiveWP embed (form-id 2804), not a Stripe
# link — so it cannot be carried across and needs a new Payment Link.
STRIPE_ONE_TIME = None  # [STRIPE LINK NEEDED]

NAV = [
    ("who-we-are.html", "Who We Are"),
    ("our-model.html", "Our Model"),
    ("schools.html", "Schools"),
    ("what-we-do.html", "What We Do"),
    ("strategic-plan.html", "Strategic Plan"),
    ("news.html", "News"),
    ("contact.html", "Contact"),
]

BANNER = "<!-- Generated by build.py — edit build.py, not this file. -->\n"

CHECK = ('<svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke-width="2.1" '
         'stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M20 6 9 17l-5-5"/></svg>')

ICONS = {
    "book": "M4 4h7a3 3 0 0 1 3 3v13a2.5 2.5 0 0 0-2.5-2H4zM24 4h-7a3 3 0 0 0-3 3v13a2.5 2.5 0 0 1 2.5-2H24z",
    "heart": "M14 23s-8-5.1-8-11a4.6 4.6 0 0 1 8-3 4.6 4.6 0 0 1 8 3c0 5.9-8 11-8 11z",
    "leaf": "M22 6c0 9-5.5 14-12 14 0-8 4.5-13 12-14zM7 23c1.5-5 4-8 8-10",
    "coin": "M14 5v18M18.5 9.2c-.9-1.3-2.6-2-4.5-2-2.5 0-4.5 1.2-4.5 3.2 0 4.4 9 2.4 9 6.8 0 2-2 3.3-4.5 3.3-2.1 0-3.9-.8-4.7-2.3",
}


def icon(kind, size=21):
    return ('<svg width="%d" height="%d" viewBox="0 0 28 28" fill="none" stroke-width="1.7" '
            'stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="%s"/></svg>'
            % (size, size, ICONS[kind]))


def head(page, title, desc, og_img="img/hero.jpg"):
    return (
        '<!doctype html>\n<html lang="en">\n<head>\n'
        '<meta charset="utf-8">\n'
        '<meta name="viewport" content="width=device-width, initial-scale=1">\n'
        "<title>%s</title>\n" % title
        + '<meta name="description" content="%s">\n' % desc
        + '<link rel="canonical" href="%s/%s">\n' % (BASE, page)
        + '<meta property="og:type" content="website">\n'
        + '<meta property="og:site_name" content="CORAfrica">\n'
        + '<meta property="og:title" content="%s">\n' % title
        + '<meta property="og:description" content="%s">\n' % desc
        + '<meta property="og:url" content="%s/%s">\n' % (BASE, page)
        + '<meta property="og:image" content="%s/%s">\n' % (BASE, og_img)
        + '<meta name="twitter:card" content="summary_large_image">\n'
        + '<link rel="icon" href="img/favicon.svg" type="image/svg+xml">\n'
        + '<link rel="preconnect" href="https://fonts.googleapis.com">\n'
        + '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>\n'
        + '<link href="https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600;700;800'
          '&amp;family=Space+Grotesk:wght@500;600;700&amp;display=swap" rel="stylesheet">\n'
        + '<link rel="stylesheet" href="%s">\n' % assetv("styles.css")
        + "</head>\n<body>\n"
        + '<a class="skip-link" href="#main">Skip to content</a>\n'
    )


def header(page):
    links = ""
    for href, label in NAV:
        cur = ' aria-current="page"' if href == page else ""
        links += '    <a href="%s"%s>%s</a>\n' % (href, cur, label)
    return (
        '<header class="site-header">\n'
        '  <a class="brand" href="index.html" aria-label="CORAfrica home">'
        '<img src="img/corafrica-lockup-white.svg" alt="CORAfrica" width="1010" height="348"></a>\n'
        '  <nav class="site-nav" id="site-nav" data-nav aria-label="Main">\n' + links + "  </nav>\n"
        '  <div class="header-actions">\n'
        '    <a class="button button--accent button--sm" href="donate.html">Donate</a>\n'
        '    <button class="nav-toggle" type="button" aria-expanded="false" aria-controls="site-nav" data-nav-toggle>\n'
        "      <span></span><span></span><span></span>\n"
        '      <span class="sr-only">Menu</span>\n'
        "    </button>\n  </div>\n</header>\n"
    )


FOOTER = """<footer class="site-footer">
  <div class="shell">
    <div class="footer-grid">
      <div class="footer-brand">
        <img src="img/corafrica-lockup-white.svg" alt="CORAfrica" width="1010" height="348">
        <p>Helping children and communities thrive. A registered <span class='nolig'>501(c)(3)</span> non-profit in the
          United States, operating in Cross River and Benue States, Nigeria.</p>
      </div>
      <div class="footer-cols">
        <div class="footer-col">
          <div class="footer-h">Nigeria</div>
          <p>No 48 Mbube Road<br>Opposite Govt. Technical College, Abakpa<br>Ogoja, Cross River State</p>
        </div>
        <div class="footer-col">
          <div class="footer-h">United States</div>
          <p>PO Box 13<br>Evans City, PA 16033</p>
        </div>
        <div class="footer-col">
          <div class="footer-h">Contact</div>
          <p><a href="mailto:info@corafrica.org.ng">info@corafrica.org.ng</a><br>
             <a href="tel:+2349153142288">+234 915 314 2288</a></p>
        </div>
      </div>
    </div>
    <div class="footer-base">
      <span>&copy; 2026 Children of Rural Africa</span>
      <span>EIN [REQUEST FROM FR. PETER] &middot; CAC/IT/NO 40479</span>
    </div>
  </div>
</footer>
<script src="SCRIPTSRC" defer></script>
</body>
</html>
"""


def hero(kicker, h1, lede, img, alt, page_hero=True, actions=""):
    cls = "hero-card hero-card--page" if page_hero else "hero-card"
    return (
        '<section class="hero">\n  <div class="%s">\n' % cls
        + '    <img src="img/%s" alt="%s" width="1400" height="560" fetchpriority="high">\n' % (img, alt)
        + '    <div class="hero-scrim"></div>\n    <div class="hero-sheen"></div>\n'
        + '    <div class="hero-body">\n'
        + '      <span class="eyebrow">%s</span>\n' % kicker
        + "      <h1>%s</h1>\n" % h1
        + "      <p>%s</p>\n" % lede
        + actions
        + "    </div>\n  </div>\n</section>\n"
    )


def sec(inner, cls="grad-paper-warm", extra="section"):
    return '<section class="%s %s">\n  <div class="shell">\n%s  </div>\n</section>\n' % (extra, cls, inner)


def sec_wide(inner, cls="grad-paper-warm", extra="section"):
    return '<section class="%s %s">\n  <div class="shell--wide">\n%s  </div>\n</section>\n' % (extra, cls, inner)


def head_block(kicker, h2, lede=None):
    o = '    <div class="section-head">\n      <p class="kicker">%s</p>\n      <h2 class="h2">%s</h2>\n' % (kicker, h2)
    if lede:
        o += '      <p class="lede">%s</p>\n' % lede
    return o + "    </div>\n"


def card(title, body, tag=None, ic=None):
    o = '      <article class="card">\n'
    if ic:
        o += '        <span class="card-icon">%s</span>\n' % icon(ic)
    if tag:
        o += '        <span class="card-tag">%s</span>\n' % tag
    return o + "        <h3>%s</h3>\n        <p>%s</p>\n      </article>\n" % (title, body)


def grid(cards, cols=3):
    return '    <div class="grid grid--%d">\n%s    </div>\n' % (cols, "".join(cards))


REVEAL = ("card", "tier", "person", "press-card", "press-row", "register-row",
          "tl-row", "photo-card", "media", "panel", "alt-row", "section-head", "cred",
          "cost-row")


def add_reveals(html):
    """Tag animatable blocks inside <main>. The chrome is left alone — a header
    that fades in on every page load is a nuisance, not a flourish."""
    i, j = html.index("<main"), html.index("</main>")
    head, main, tail = html[:i], html[i:j], html[j:]

    def hook(m):
        cls = m.group(1)
        if any(c in cls.split() for c in REVEAL) and "data-reveal" not in m.group(0):
            return 'class="%s" data-reveal' % cls
        return m.group(0)

    return head + re.sub(r'class="([^"]+)"', hook, main) + tail


def write(page, html):
    html = add_reveals(html)
    html = html.replace("SCRIPTSRC", assetv("script.js"))
    path = os.path.join(OUT, page)
    open(path, "w", encoding="utf-8").write(html)
    print("%-24s %6d bytes" % (page, len(html)))


# ============================================================== shared data
STATS = [("2,000+", "Pupils educated", "At St. Joseph&rsquo;s, Idum-Mbube alone"),
         ("500+", "Women financed", "Soft loans and grants to date"),
         ("5", "Schools founded", "Across Cross River State"),
         ("2", "Centres running", "Mbube-Ogoja and Victoria-Ikom")]

PILLARS = [("Education", "Primary and secondary schools, built where no school exists, plus vocational and skills centres.", "book"),
           ("Healthcare", "A clinic on the school site, and care concentrated on a child&rsquo;s first 1,000 days.", "heart"),
           ("Agriculture", "A demonstration farm that feeds the school and teaches the trade hands-on.", "leaf"),
           ("Livelihoods", "Soft loans so a parent can build a business and afford to keep a child in class.", "coin")]

CREDS = ["Registered <span class='nolig'>501(c)(3)</span> since 2006", "Cross River and Benue States",
         "Aligned to five UN SDGs", "Partnered with the Diocese of Ogoja"]

PRESS = [("National Catholic Reporter", "May 2024",
          "Catholic-run CORAfrica aims to fill learning gap fueled by poverty in Nigeria",
          "Valentine Benjamin reports from Ogoja on the schools, the empowerment programme and the families behind the numbers.",
          "https://www.ncronline.org/news/catholic-run-corafrica-aims-fill-learning-gap-fueled-poverty-nigeria"),
         ("Vanguard", "July 2026",
          "CORAfrica expands community development through education, healthcare, livelihood programmes",
          "A full account of the Community Education Centre model, our partners, and our alignment to the UN Sustainable Development Goals.",
          "https://www.vanguardngr.com/2026/07/corafrica-expands-community-development-efforts-through-education-healthcare-livelihood-programmes/"),
         ("ThisDay", "July 2026",
          "CORAfrica expands access to education for children in rural communities",
          "On the new classroom block at John Stilley Secondary School and the six-classroom block at St. Peter&rsquo;s, Adagom 3.",
          "https://www.thisdaylive.com/2026/07/30/corafrica-expands-access-to-education-for-children-in-rural-communities/"),
         ("CrossRiverWatch", "September 2015",
          "Community Champion: how a Catholic priest is empowering orphans in Cross River State",
          "An early profile of Fr. Peter Abue and the founding work of CORAfrica.",
          "https://crossriverwatch.com/2015/09/community-champion-how-a-catholic-priest-is-empowering-orphans-in-cross-river-state/"),
         ("CrossRiverWatch", "November 2014",
          "US Country Representative of Children of Rural Africa rounds off visit to Cross River",
          "Coverage of the American board&rsquo;s visit to the projects in Cross River State.",
          "http://crossriverwatch.com/2014/11/us-country-rep-of-children-of-rural-africa-rounds-off-visit-to-cross-river/")]

SCHOOL_CARDS = [("300+ students", "John Stilley Secondary School", "school.jpg",
                 "Victoria, Ikom &mdash; the only secondary school in its community"),
                ("Founded 2020", "John Bosco Academy", "hands.jpg",
                 "Adagom, Ogoja &mdash; for refugee children arriving from Cameroon"),
                ("2,000+ pupils", "St. Joseph&rsquo;s School", "clinic.jpg",
                 "Idum-Mbube &mdash; school and orphanage, now run by the Diocese of Ogoja")]


def stats_panel():
    s = ""
    for n, l, note in STATS:
        s += ('        <div>\n          <div class="stat-n">%s</div>\n'
              '          <div class="stat-l">%s</div>\n'
              '          <div class="stat-note">%s</div>\n        </div>\n' % (n, l, note))
    return ('    <div class="panel">\n'
            '      <div class="panel-head">\n'
            '        <p class="kicker">Twenty years on the ground</p>\n'
            '        <p class="panel-note">Independently reported &mdash; National Catholic Reporter, Vanguard, ThisDay</p>\n'
            "      </div>\n"
            '      <div class="stats">\n%s      </div>\n    </div>\n' % s)


def creds_strip():
    c = ""
    for x in CREDS:
        c += '      <div class="cred">%s<span>%s</span></div>\n' % (CHECK, x)
    return '    <div class="credentials">\n%s    </div>\n' % c


def donate_band():
    return ('    <div class="panel panel--dark">\n      <div class="donate-band">\n'
            "        <div>\n"
            '          <p class="kicker kicker--light">Support the work</p>\n'
            "          <h2>&#8358;150,000 started a business. $40,000 started a programme.</h2>\n"
            "          <p>CORAfrica is a registered <span class='nolig'>501(c)(3)</span> in the United States, so gifts from US donors "
            "are tax-deductible. Give monthly, and we can plan.</p>\n"
            "        </div>\n"
            '        <div class="donate-actions">\n'
            '          <a class="button button--accent" href="%s" rel="noopener">Give $25 a month</a>\n' % STRIPE_25_MONTHLY
            + '          <a class="button button--onDark" href="donate.html">Other ways to give</a>\n'
            + '          <p class="donate-fine">Processed securely by Stripe</p>\n'
            "        </div>\n      </div>\n    </div>\n")


# ============================================================== index
body = hero("Education for Africa&rsquo;s Future",
            "A school, and everything that keeps a child in it.",
            "CORAfrica builds primary and secondary schools in rural Nigeria where none exist &mdash; then adds "
            "the clinic, the farm and the workshop that keep children coming back. Founded 2006. Working across "
            "Cross River and Benue States.",
            "hero.jpg", "Pupils at their desks at a CORAfrica school", page_hero=False,
            actions='      <div class="button-row">\n'
                    '        <a class="button button--accent" href="donate.html">Donate</a>\n'
                    '        <a class="button button--onDark" href="contact.html">Partner with us</a>\n'
                    "      </div>\n")
body += sec(creds_strip(), cls="bg-paper", extra="section--flush-top")
body += sec_wide(stats_panel(), cls="grad-paper-warm", extra="section--tight")
body += sec('    <div class="split split--center">\n      <div>\n'
            + head_block("The Community Education Centre",
                         "A school on its own does not keep a child in school.",
                         "Hunger, illness, and a family with no income take more children out of class than any exam "
                         "does. So our model puts four things on one site, and treats them as one system rather than "
                         "four programmes. Two centres are running today, at Mbube-Ogoja and Victoria-Ikom.")
            + '        <a class="button button--dark" href="strategic-plan.html">Read the strategic plan</a>\n'
            + "      </div>\n"
            + grid([card(n, b, ic=i) for n, b, i in PILLARS], 2)
            + "    </div>\n", cls="grad-warm-white")

sc = ""
for tag, name, img, note in SCHOOL_CARDS:
    sc += ('      <a class="photo-card" href="schools.html">\n'
           '        <img src="img/%s" alt="%s" loading="lazy" width="900" height="675">\n' % (img, name)
           + '        <div class="photo-card-body">\n'
           + '          <span class="photo-card-tag">%s</span>\n          <h3>%s</h3>\n          <p>%s</p>\n' % (tag, name, note)
           + "        </div>\n      </a>\n")
body += sec_wide(head_block("Our schools", "Built where there was nothing.")
                 + grid([sc], 3), cls="grad-white-strong")

body += sec('    <div class="split split--media split--center">\n'
            '      <div class="media"><img src="img/founder.jpg" alt="Fr. Peter Abue with pupils" loading="lazy" width="900" height="675"></div>\n'
            "      <div>\n"
            + head_block("Our founder",
                         "&ldquo;Most of my peers in our village could not. So I decided to fill that gap.&rdquo;",
                         "Fr. Peter Obele Abue conceived CORAfrica in 2006 while completing a PhD in International "
                         "Development at Cornell. He holds a Master&rsquo;s in Corporate Communication from Duquesne, "
                         "and is Vicar General of the Catholic Diocese of Ogoja. The schools, clinics and farms he "
                         "founds are handed over to be owned and run by his home diocese &mdash; the work is built to "
                         "outlast him.")
            + '        <p class="byline"><span class="alt-rule"></span><span>Fr. Peter Obele Abue &middot; Founder</span></p>\n'
            + "      </div>\n    </div>\n", cls="grad-strong-paper")

pc = ""
for outlet, date, title, blurb, url in PRESS[:3]:
    pc += ('      <a class="press-card" href="%s" rel="noopener">\n' % url
           + '        <div class="press-card-top"><span class="press-outlet">%s</span>'
             '<span class="press-date">%s</span></div>\n' % (outlet, date)
           + "        <h3>%s</h3>\n" % title
           + '        <span class="press-go">Read the article &rarr;</span>\n      </a>\n')
body += sec(head_block("In the news", "Reported independently.") + grid([pc], 3), cls="bg-paper")
body += sec_wide(donate_band(), cls="bg-paper", extra="section--flush-top section--tight")

write("index.html",
      head("index.html", "CORAfrica — Children of Rural Africa",
           "CORAfrica builds primary and secondary schools in rural Nigeria, then adds the clinics, farms and "
           "vocational centres that keep children in class. A registered 501(c)(3) founded in 2006.")
      + BANNER + header("index.html") + '<main id="main">\n' + body + "</main>\n" + FOOTER)


# ============================================================== who-we-are
HISTORY = [
    ("2006", "Conceived at Cornell",
     "Fr. Peter Obele Abue, completing a PhD in International Development at Cornell University, sets out to close the gap he had watched open between the developed and the developing world."),
    ("2006", "Incorporated in the United States",
     "CORAfrica is granted <span class='nolig'>501(c)(3)</span> non-profit status, with a founding Board of Trustees of Bruno Schickel, Royal Colle, Thomas Lickona and Carolann Darling. Building begins in Nigeria that same year."),
    ("2009", "Fr. Peter returns to Nigeria",
     "Empowerment programmes and projects follow across the Diocese of Ogoja &mdash; St. Joseph&rsquo;s Primary and Secondary School, the Sr. Augustina Abuo Medical Clinic, Little Flower School at Ipong-Obudu."),
    ("2010", "Registered in Nigeria",
     "CORAfrica is incorporated under the Companies and Allied Matters Act on 6 September 2010 as a Registered Trustee of an NGO, certificate CAC/IT/NO 40479 &mdash; giving the work a legal footing in both countries it operates in."),
    ("2010s", "A second board, from Western Pennsylvania",
     "Ray Ferguson, Fr. Jim Murphy, Anne Goetler, Tom Rooney, Jeannine Goetz and Ethan Suquet join. With Abode for Children Inc. of Evans City, led by Tom and Mary Rutkoski, they upgrade St. Joseph&rsquo;s Schools and Orphanage and CORAfrica Farms."),
    ("2020", "John Bosco Academy",
     "Founded at Adagom, Ogoja, to reach the influx of refugee children arriving from Cameroon with no access to basic education."),
    ("2021", "The John Stilley Schools",
     "Founded at Victoria, Ikom, where no secondary school existed. St. Peter&rsquo;s Primary is registered at Adagom 3. John Stilley and his family have given time, funds and energy to make these projects last."),
    ("Today", "Two states, and a model that travels",
     "Headquartered in Abuja, CORAfrica works across Cross River and Benue States, reaching rural communities, IDP camps and refugee settlements."),
]
VALUES = [
    ("Dignity of the human person", "Each person &mdash; each child &mdash; has an inalienable dignity, and should be treated as an end and never only as a means. Every child deserves the chance to achieve their dreams, no matter where they were born."),
    ("Solidarity and the common good", "Faced with globalisation and the growing interdependence of peoples, the universal human family remains one. We are obliged to increase our sensitivity toward children, especially those who suffer deprivation."),
    ("Self-reliance", "We look for the explicit ways a community or institution can design its structures so that children and young people become independent &mdash; rather than relying permanently on outside intervention."),
]

tl = ""
for yr, t, b in HISTORY:
    tl += ('      <div class="tl-row">\n        <div class="tl-year">%s</div>\n'
           "        <div><h3>%s</h3><p>%s</p></div>\n      </div>\n" % (yr, t, b))

body = hero("Who we are", "Twenty years of building schools where there were none.",
            "CORAfrica is a development agency with <span class='nolig'>501(c)(3)</span> status in the United States and operations across rural "
            "Nigeria. We believe a child&rsquo;s education is inseparable from their health, their food and their "
            "family&rsquo;s income &mdash; so we build all four.",
            "founder.jpg", "Fr. Peter Abue with pupils")
body += sec('    <div class="grid grid--2">\n'
            '      <article class="card"><p class="kicker">Our vision</p>'
            '<h3 style="font-family:\'Space Grotesk\',sans-serif;font-size:28px;line-height:1.16;letter-spacing:-.04em">'
            "To impact the lives of children throughout Africa, beginning with Nigeria.</h3></article>\n"
            '      <article class="card"><p class="kicker">Our mission</p>'
            '<h3 style="font-family:\'Space Grotesk\',sans-serif;font-size:28px;line-height:1.16;letter-spacing:-.04em">'
            "To change the face of education and healthcare for indigent children in Africa, one community at a time.</h3></article>\n"
            "    </div>\n", cls="grad-paper-warm", extra="section--tight")
body += sec('    <div class="split split--center">\n'
            '      <div style="text-align:center"><img src="img/corafrica-seal.svg" alt="The CORAfrica seal" '
            'style="width:230px;margin-inline:auto" loading="lazy" width="292" height="292"></div>\n'
            "      <div>\n"
            + head_block("Our logo", "The map, and the light.",
                         "The seal carries the map of Africa and a torch. The torch stands for the Light our "
                         "programmes are meant to bring &mdash; the conviction that education is what changes a "
                         "continent&rsquo;s prospects, one community at a time. The ring around it carries our name "
                         "and our promise: <em>Helping Children and Communities Thrive</em>.")
            + "      </div>\n    </div>\n", cls="grad-warm-white")
body += sec(head_block("Our history", "From a doctorate to a network of schools.") + tl,
            cls="bg-white", extra="section--flush-top section")
body += sec(head_block("Our philosophy", "Three convictions we build on.",
                       "CORAfrica&rsquo;s philosophy is rooted in Catholic Social Teaching, and reduces to three core "
                       "values that govern how we choose projects and how we hand them on.")
            + grid([card(t, b) for t, b in VALUES], 3), cls="grad-white-strong")
# Registration and audit detail, from the 2025 financial report. This is the
# section a grants officer looks for first, and it was missing entirely.
body += sec(head_block("Accountability", "Registered, audited, and on the record.",
                       "We are a registered charity in both countries we work in, our books are audited annually by "
                       "an independent firm, and our accounts are available to funders on request.")
            + grid([card("Registered in Nigeria", "Incorporated under the Companies and Allied Matters Act on 6 September 2010 as a Registered Trustee of an NGO. Certificate CAC/IT/NO 40479.", "Since 2010"),
                    card("Registered in the United States", "A <span class='nolig'>501(c)(3)</span> non-profit, so gifts from US taxpayers are tax-deductible. EIN [REQUEST FROM FR. PETER].", "Since 2006"),
                    card("Independently audited", "Our financial statements are audited by Akomaye Adie &amp; Co., Chartered Accountants and Tax Practitioners, of Calabar.", "Annually"),
                    card("92.6% to programmes", "Of everything CORAfrica spent in the year ended 31 December 2025, 92.6% went to schools, clinics, farms and loan funds. Overheads were 7.4%.", "2025 accounts"),
                    card("Assets we hold", "Land, school buildings and a farm and agricultural station, carried in the 2025 accounts at &#8358;180.5 million.", "2025 accounts"),
                    card("Governed by trustees", "A Board of Trustees oversees the organisation, with operations directed from Ogoja in Cross River State.", "Governance")], 3),
            cls="grad-paper-warm")
write("who-we-are.html", head("who-we-are.html", "Who We Are — CORAfrica",
      "Our vision, mission, history and philosophy. CORAfrica has built schools in rural Nigeria since 2006, "
      "rooted in Catholic Social Teaching.", "img/founder.jpg")
      + BANNER + header("who-we-are.html") + '<main id="main">\n' + body + "</main>\n" + FOOTER)


# ============================================================== our-model
COMPONENTS = [
    ("Education", "hands.jpg", "01",
     "Primary and secondary schools, built where children have no educational opportunity at all, and educational amenities supplied where schools exist but lack them. Small classes, high-quality instruction, and a holistic education that grows a child academically, personally and spiritually."),
    ("Healthcare", "clinic.jpg", "02",
     "A clinic inside the school system, so a child&rsquo;s health is not a reason to miss class. Particular emphasis on diarrhoeal disease and malaria in the under-fives, and heavy investment in the first 1,000 days of life &mdash; the window that sets brain development, growth and immune strength."),
    ("Agriculture", "farm.jpg", "03",
     "Agricultural centres and school farms where children learn agriculture with their hands, not from a textbook. The farm feeds the school, and the skill outlasts the schooling."),
    ("Economic empowerment", "empower.jpg", "04",
     "Where a family cannot afford to keep a child in class, the barrier is income. Soft loans let poor parents start small businesses and farms. More than 500 women have been supported this way."),
]
blocks = ""
for i, (name, img, num, txt) in enumerate(COMPONENTS):
    media = ('        <div class="media"><img src="img/%s" alt="%s" loading="lazy" width="900" height="675"></div>\n'
             % (img, name))
    copy = ('        <div>\n          <p class="alt-num"><span>%s</span><span class="alt-rule"></span></p>\n'
            "          <h3>%s</h3>\n          <p>%s</p>\n        </div>\n" % (num, name, txt))
    blocks += '      <div class="alt-row">\n%s      </div>\n' % ((media + copy) if i % 2 == 0 else (copy + media))

body = hero("Our model", "Four components. One site. One system.",
            "The Community Education Centre is our answer to a hard lesson: a school on its own does not keep a child "
            "in school. Hunger, illness and a family without income take more children out of class than any exam does.",
            "farm.jpg", "A CORAfrica demonstration farm")
body += sec(head_block("The Community Education Centre",
                       "Built from what actually keeps children out of class.",
                       "Each CEC combines a primary and secondary school, a medical clinic with a running water "
                       "system, an agricultural demonstration farm, and a vocational and skills acquisition centre. "
                       "Children learn from the school and the community at once, with hands-on experience in each.")
            + blocks, cls="grad-paper-warm")
body += sec(head_block("Where we operate", "Two centres running, and a model designed to travel.",
                       "Our two Community Education Centres are at Mbube-Ogoja and Victoria-Ikom. We are seeking "
                       "funding to equip and operate both to their full plan. Our wider work reaches rural "
                       "communities, IDP camps and refugee settlements across Cross River and Benue States.")
            + grid([card("Mbube-Ogoja", "Home of St. Joseph&rsquo;s Primary and Secondary School and the Sr. Augustina Abuo Medical Clinic.", "Centre one"),
                    card("Victoria-Ikom", "Home of the John Stilley Schools, founded where the community had no secondary school at all.", "Centre two"),
                    card("Adagom, Ogoja", "John Bosco Academy and St. Peter&rsquo;s Primary, serving refugee and host communities together.", "Refugee response")], 3),
            cls="grad-white-strong")
write("our-model.html", head("our-model.html", "Our Model — CORAfrica",
      "The Community Education Centre: education, healthcare, agriculture and economic empowerment on one site, "
      "because a school alone does not keep a child in school.", "img/farm.jpg")
      + BANNER + header("our-model.html") + '<main id="main">\n' + body + "</main>\n" + FOOTER)


# ============================================================== what-we-do
VASAC = [
    ("Computer studies", "Functional computer laboratories with stable connectivity, reliable power with backup, trained ICT staff and proper security."),
    ("Fashion design", "Sewing, pattern drafting and fabric selection &mdash; creativity and entrepreneurship, with income from garment production."),
    ("Beauty &amp; aesthetics", "Hairdressing, make-up artistry and skincare, with the customer-service grounding that makes self-employment viable."),
    ("Home economics", "Cooking, nutrition, budgeting, childcare and household management &mdash; supporting healthy living and catering businesses."),
    ("Music", "Performance, production and teaching. Discipline, confidence and teamwork, with a route into content creation."),
    ("Technical drawing", "Precise drawing for engineering and architecture &mdash; critical thinking, and the foundation for every technical trade."),
    ("Visual arts", "Creativity, innovation and communication, with income from art sales and design services across the creative industries."),
    ("Building trades", "Masonry, blocklaying and concreting, carpentry and joinery, furniture and upholstery, plumbing, tiling, painting and interior finishing, aluminium work, and solar PV installation and maintenance."),
    ("Agriculture", "Mechanised agriculture and operations, and livestock farming &mdash; beekeeping, poultry and animal husbandry."),
]
RIGHTS = [
    "Every child has the right to a standard of living adequate for their health and well-being.",
    "Every child has the right to learn how to work, to free choice of employment, to just and favourable conditions of work, and to protection against unemployment.",
    "Everyone, without discrimination, has the right to equal pay for equal work.",
    "Everyone who works has the right to remuneration that ensures an existence worthy of human dignity for themselves and their family.",
]
rl = ""
for r in RIGHTS:
    rl += '      <div class="belief">%s<p>%s</p></div>\n' % (CHECK, r)

body = hero("What we do", "Education is the bedrock. Everything else is built on it.",
            "Getting a good education as a child is the essential building block of a tolerant, well-adjusted, healthy "
            "and prosperous adult. Families where parents completed primary and secondary school have higher incomes, "
            "better health and longer lives &mdash; and pass all of it on.",
            "hands.jpg", "Children at a CORAfrica school")
body += sec(head_block("Education", "A high-quality education is an inherent right of every child.",
                       "We build and equip primary and secondary schools in rural areas, creating sustainable "
                       "livelihoods for indigent children and preventing the poverty, abuse and exploitation that "
                       "follow when a child is out of school.")
            + grid([card("Primary and secondary", "Conventional schooling, run properly &mdash; small classes, quality instruction, and preparation for an increasingly globalised world."),
                    card("Holistic by design", "Children are encouraged to grow academically, personally and spiritually, in an environment of curiosity, creativity and enthusiasm."),
                    card("Tertiary and vocational", "Our educational component runs from primary through secondary to tertiary support and vocational skills acquisition.")], 3),
            cls="grad-paper-warm")
body += sec(head_block("VASAC", "Vocational and Skills Acquisition Centres.",
                       "We go a step beyond the conventional school system and equip our schools so students leave "
                       "with a trade. Each centre runs pilot systems where students practise the skills that will "
                       "sustain them for life &mdash; actively involved, hands-on, in every area below.")
            + grid([card(t, b) for t, b in VASAC], 3)
            + grid([card("Staffing", "Reputable staff recruited from known institutions, with experts drawn from local artisans known to us over many years &mdash; administrative staff, professional teachers and skilled labourers."),
                    card("Equipment and certification", "Every department furnished and equipped to match its training. Partnerships with donors and bilateral organisations are intended to carry students through to certification and job placement.")], 2),
            cls="grad-warm-white")
body += sec(head_block("Healthcare", "A child too ill to learn is not being educated.",
                       "We establish health clinics inside the school system, and teach healthcare awareness and "
                       "sanitation as part of school life. We place particular emphasis on preventing and treating "
                       "diarrhoeal disease and malaria in children under five, and on the first 1,000 days of life. "
                       "Our investment extends to the health of their mothers.")
            + grid([card("Preventive first", "Preventive care, combating malnutrition, and community education on preventing the transmission of HIV."),
                    card("Community health workers", "A growing team providing health education and accompanying families through the process of seeking care."),
                    card("Water and sanitation", "Practical hand-washing hygiene, toilets, and water collection and treatment &mdash; taught in school, extended into the community and to refugee settlements.")], 3),
            cls="bg-white")
body += sec_wide('    <div class="panel panel--dark">\n      <p class="kicker kicker--light">What we believe</p>\n'
                 '      <h2 class="h2" style="color:#fff;margin-bottom:1.6rem">In CORAfrica, we hold that:</h2>\n'
                 + rl + "    </div>\n", cls="grad-white-strong", extra="section--flush-top section")
write("what-we-do.html", head("what-we-do.html", "What We Do — CORAfrica",
      "Education, vocational and skills acquisition centres, and healthcare. The nine trades our VASAC programme "
      "teaches, and the clinics we run inside our schools.", "img/hands.jpg")
      + BANNER + header("what-we-do.html") + '<main id="main">\n' + body + "</main>\n" + FOOTER)


# ============================================================== schools
REGISTER = [
    ("John Stilley Secondary School", "Victoria, Ikom", "2021", "300+ students", "Founded where the community had no secondary school at all. A new classroom block has since been added, supported by the John Stilley Family Trust Fund."),
    ("John Bosco Academy", "Adagom, Ogoja", "2020", "479 pupils", "Founded to reach the high influx of refugee children arriving from Cameroon who could not access basic and quality education. Four in five of its pupils are refugee children. It now runs a primary section of 343 and a secondary section of 136, taught by 28 staff, and an academic block for science and the skilled trades is going up on the compound. Formerly St. Peter&rsquo;s Catholic School."),
    ("St. Peter&rsquo;s Primary School", "Adagom 3, Ogoja", "2021", "300+ pupils", "Registered with the education authorities in June 2021. A six-classroom block serves children from both refugee and host communities who cannot afford school fees."),
    ("St. Joseph&rsquo;s Primary &amp; Secondary", "Idum-Mbube, Ogoja", "&mdash;", "2,000+ pupils", "Also an orphanage, caring for children from five years and above. Now handed over to be owned and run by the Diocese of Ogoja &mdash; as our projects are designed to be."),
    ("Little Flower Nursery &amp; Primary", "Ipong-Obudu", "&mdash;", "Nursery &amp; primary", "One of the earliest schools initiated across the diocese, and part of the network that established the model we now build to."),
    ("Thomas McGettrick Institute of Technology", "Ogoja Diocese", "&mdash;", "Technical", "A technical institute among the projects facilitated in collaboration with the diocesan bishops, and since handed on."),
]
rows = ""
for name, place, yr, stat, note in REGISTER:
    rows += ('      <article class="register-row">\n'
             "        <div><h3>%s</h3>\n" % name
             + '          <div class="r-pills"><span class="is-stat">%s</span><span>%s</span><span>%s</span></div>\n' % (stat, place, yr)
             + "          <p>%s</p></div>\n" % note
             + '        <div class="r-meta">%s</div>\n        <div class="r-year">%s</div>\n'
               '        <div class="r-stat">%s</div>\n      </article>\n' % (place, yr, stat))

body = hero("Our schools", "Built where there was nothing.",
            "We found schools where the need is greatest &mdash; and then hand them over to be owned and run by the "
            "local diocese. The work is built to outlast whoever started it.",
            "school.jpg", "John Stilley Secondary School")
body += sec(head_block("The register", "Every school CORAfrica has founded or upgraded.",
                       "Some of these are now run by the Diocese of Ogoja. That is the intended end state, not a loss "
                       "&mdash; a project that cannot be handed on has not really been built.")
            + '    <div class="register-head"><span>School</span><span>Location</span><span>Founded</span><span>Scale</span></div>\n'
            + rows, cls="grad-paper-warm")
body += sec(head_block("Also under our care", "Clinics, farms and empowerment programmes.")
            + grid([card("Sr. Augustina Abuo Medical Clinic", "Idum-Mbube. The health component of the Mbube Community Education Centre.", "Health"),
                    card("CORAfrica Farms", "Demonstration farms feeding the schools and teaching mechanised agriculture and livestock.", "Agriculture"),
                    card("ODAIP", "The Ogoja Diocesan Agriculture and Investment Programme, run in collaboration with the diocese.", "Agriculture"),
                    card("St. Thomas Aquinas Programme", "Economic empowerment, launched in 2022 with $40,000 and commissioned by Bishop Donatus Akpan.", "Livelihoods"),
                    card("Holy Family Parish Programme", "Economic empowerment at Ikom, giving parishioners access to funds for small and larger enterprises.", "Livelihoods"),
                    card("Help-a-Kid", "Scholarships for children who cannot afford fees, with educational materials and school uniforms provided.", "Scholarships")], 3),
            cls="grad-white-strong")
write("schools.html", head("schools.html", "Our Schools — CORAfrica",
      "The register of every school CORAfrica has founded or upgraded across Cross River State, plus the clinics, "
      "farms and empowerment programmes under our care.", "img/school.jpg")
      + BANNER + header("schools.html") + '<main id="main">\n' + body + "</main>\n" + FOOTER)


# ============================================================== strategic-plan
body = hero("Our strategic plan", "What we are building next.",
            "Our plan concerns the development of children in rural Nigeria, and the operational capacity and "
            "administration to deliver it &mdash; all within the setting of the Community Education Centre model.",
            "empower.jpg", "The economic empowerment programme")
# John Bosco University and the Adagom academic building are the two live capital
# priorities, from Fr. Peter's Mission Showcase one-pager and the Adagom proposal.
# Neither appears in the docx or on the existing site.
body += sec(head_block("The priority", "John Bosco University.",
                       "Our biggest and most urgent undertaking is a university at Ogoja that would not simply grant "
                       "degrees. It would form teachers, health workers, agricultural leaders, entrepreneurs, "
                       "peacebuilders and Catholic servant-leaders who do not forget where they came from &mdash; "
                       "young men and women able to rebuild rural communities from within. It is the next step after "
                       "twenty years of primary and secondary schools.")
            + grid([card("What it needs", "Approximately <strong>US $2 million</strong> in foundational support to move the university from vision to reality.", "Capital"),
                    card("What we are looking for", "Mission partners, capital support, Catholic academic partnerships, university-development expertise and scholarship donors.", "Partnership"),
                    card("Why now", "Our secondary schools are producing graduates who have nowhere in the region to go on to. The university closes the last gap in the path we have already built.", "Rationale")], 3),
            cls="grad-paper-warm")

body += sec(head_block("Under construction", "The academic building at John Bosco Academy, Adagom.",
                       "A 56 by 13.5 metre academic block begun in January 2025 with John Stilley and Franciscan "
                       "University of Steubenville. It houses an assembly hall, two computer laboratories and science "
                       "laboratories, alongside workshops for fashion design, home economics, beauty and aesthetics, "
                       "technical drawing, visual arts, music, and photography and videography. Completion is costed "
                       "at <strong>US $129,158.62</strong>.")
            + grid([card("Completing the building", "Ceiling, fenestration, plumbing, electrical works, plastering and external works on the administrative block.", "$62,441"),
                    card("Computer laboratories", "Two hundred computer sets, networking, printers and power backup &mdash; enough to accredit the school as a WAEC and JAMB computer-based testing centre, which then earns income of its own.", "$42,069"),
                    card("Science laboratories", "Chemistry, physics and biology: benching, equipment and reagents.", "$13,269"),
                    card("Furniture and equipment", "Desks, chairs, boards, fans and a generator for the assembly hall and the skills workshops.", "$11,379"),
                    card("Who it serves", "The academy&rsquo;s 479 pupils &mdash; 343 in the primary section and 136 in the secondary &mdash; taught by 28 staff. Four in five are refugee children.", "Reach"),
                    card("What it produces", "Around 100 young people a year trained in employable trades, with half the places reserved for women and girls.", "Outcome")], 3),
            cls="grad-white-strong")

body += sec(head_block("The method", "Study teams, not just classes.",
                       "Through our Vocational and Skills Acquisition Centres, pilot systems are operated in which "
                       "children and young people form study teams together with parents, teachers and community "
                       "members. A skill practised alongside the adults who will employ or finance it is a skill "
                       "that survives leaving school.")
            + grid([card("Community Education Centre model", "Extending the four-component centre to further communities, and fully equipping the two that already run at Mbube-Ogoja and Victoria-Ikom.", "Programme in view"),
                    card("The Children&rsquo;s Hospital Project", "A dedicated children&rsquo;s hospital, extending the school-clinic model into full paediatric care. [SCOPE AND COST TO BE CONFIRMED]", "Programme in view"),
                    card("The VASAC Project", "Purpose-built vocational and skills acquisition centres, equipped across all nine trade areas, with certification and job placement partnerships. [SCOPE AND COST TO BE CONFIRMED]", "Programme in view")], 3),
            cls="grad-warm-white")
body += sec(head_block("Alignment", "Where our work meets the global agenda.",
                       "CORAfrica&rsquo;s programmes are aligned to five United Nations Sustainable Development "
                       "Goals. Our livelihood strategy seeks to improve access to food, healthcare, education, clean "
                       "water and skills development for vulnerable households, with particular emphasis on rural women.")
            + grid([card("No poverty", "Reducing poverty through education, and through soft loans that let a family build an income."),
                    card("Zero hunger", "Food security through demonstration farms and school feeding."),
                    card("Gender equality", "Increasing rural women&rsquo;s access to livelihood opportunities, agricultural resources and women-led enterprise."),
                    card("Decent work", "Vocational and skills training that leads to sustainable, dignified livelihoods."),
                    card("Reduced inequality", "Reaching refugee, IDP and host communities together, without distinction."),
                    card("Partnerships", "Working with communities, dioceses, institutions and bilateral organisations rather than around them.")], 3),
            cls="grad-paper-warm")
write("strategic-plan.html", head("strategic-plan.html", "Our Strategic Plan — CORAfrica",
      "John Bosco University, the academic building at Adagom, and the Community Education Centre model \u2014 "
      "what CORAfrica is building next in rural Cross River State.", "img/empower.jpg")
      + BANNER + header("strategic-plan.html") + '<main id="main">\n' + body + "</main>\n" + FOOTER)


# ============================================================== news
items = ""
for outlet, date, title, blurb, url in PRESS:
    items += ('      <article class="press-row">\n'
              '        <div><div class="press-outlet">%s</div><div class="press-date">%s</div></div>\n' % (outlet, date)
              + "        <div><h3>%s</h3><p>%s</p></div>\n" % (title, blurb)
              + '        <div class="press-go"><a href="%s" rel="noopener">Read &rarr;</a></div>\n      </article>\n' % url)

body = ('<section class="page-hero-light grad-white-paper">\n  <div class="shell">\n'
        '    <p class="kicker">In the news</p>\n'
        "    <h1>CORAfrica, reported independently.</h1>\n"
        '    <p class="lede">Our work has been covered by the National Catholic Reporter and by two of '
        "Nigeria&rsquo;s largest national dailies. Where we make a claim on this site, these are the places you can "
        "check it.</p>\n  </div>\n</section>\n")
body += sec(items, cls="grad-paper-warm", extra="section--flush-top section")
body += sec(head_block("Press enquiries", "For interviews, images or further information.",
                       "Contact our office in Ogoja and we will put you in touch with Fr. Peter Abue or the relevant "
                       "programme lead.")
            + '    <div class="button-row">\n'
              '      <a class="button button--accent" href="mailto:info@corafrica.org.ng">info@corafrica.org.ng</a>\n'
              '      <a class="button button--plain" href="tel:+2349153142288">+234 915 314 2288</a>\n    </div>\n',
            cls="grad-white-strong")
write("news.html", head("news.html", "In the News — CORAfrica",
      "CORAfrica in the National Catholic Reporter, Vanguard, ThisDay and CrossRiverWatch.")
      + BANNER + header("news.html") + '<main id="main">\n' + body + "</main>\n" + FOOTER)


# ============================================================== donate
amounts = ""
for amt, url in STRIPE_MONTHLY:
    amounts += ('      <a class="amount" href="%s" rel="noopener">\n'
                '        <span class="amount-n">$%s</span>\n'
                '        <span class="amount-per">a month</span>\n      </a>\n' % (url, amt))

body = hero("Donate", "&#8358;150,000 started a business. $40,000 started a programme.",
            "Ada Okoli took a &#8358;150,000 soft loan in 2022 and turned a small trade into a wholesale and retail "
            "business. The St. Thomas Aquinas empowerment programme launched with $40,000 and has since supported "
            "more than 500 women. Small sums, placed carefully, compound.",
            "hero.jpg", "Pupils at a CORAfrica school")

body += sec(head_block("Give monthly", "Monthly gifts are what let us plan.",
                       "A school year is twelve months long, and so is a teacher&rsquo;s salary. Recurring gifts are "
                       "worth far more to us than their size suggests, because they are the only kind we can build a "
                       "budget on. Choose an amount and Stripe handles the rest.")
            + '    <div class="amounts">\n' + amounts + "    </div>\n"
            + '    <p class="amounts-note">Gifts are unrestricted unless you tell us otherwise, so we can put them '
              "where the need is sharpest. What those amounts buy, at the prices we are actually paying, is set out "
              "below.</p>\n",
            cls="grad-paper-warm")

# Real unit costs, from the line-item budget of the Adagom academic building
# proposal (converted at the proposal's own rate of N1,450 to the dollar).
# Deliberately framed as a price list, not as a promise about where a given
# dollar lands — that distinction matters and is item 9 in ASK-FR-PETER.md.
COSTS = [("$3", "a set of wall charts for a classroom"),
         ("$14", "a laboratory stool"),
         ("$34", "a school desk"),
         ("$55", "a whiteboard, or a ceiling fan for a classroom in 35&deg;C heat"),
         ("$172", "one computer &mdash; and the school needs two hundred of them"),
         ("$3,448", "every reagent the chemistry, physics and biology laboratories need"),
         ("$8,352", "the full equipment fit-out of all three science laboratories"),
         ("$13,269", "a complete science laboratory, built and stocked")]
costs = ""
for amt, what in COSTS:
    costs += ('      <div class="cost-row"><span class="cost-n">%s</span>'
              '<span class="cost-w">%s</span></div>\n' % (amt, what))

body += sec(head_block("What it buys", "These are the prices we are paying.",
                       "Not illustrations. Every figure below is a line in the costed budget for the academic "
                       "building now going up at John Bosco Academy in Adagom, where four out of five pupils are "
                       "refugee children from Cameroon. Converted at &#8358;1,450 to the dollar.")
            + '    <div class="costs">\n' + costs + "    </div>\n",
            cls="grad-warm-white")

SPLIT = [("71.7%", "<strong>Education.</strong> The academic and administrative block at John Bosco Academy, "
                   "fencing and landscaping at both academies, a bus for secondary students, a lodge for the youth "
                   "corps teachers, and the cost of running the schools."),
         ("10.0%", "<strong>Economic empowerment.</strong> Interest-free micro-loans to small businesses, and "
                   "outright grants to widows and to vulnerable families."),
         ("6.2%", "<strong>Health.</strong> Medical outreach at Victoria, drugs and medical supplies, and running "
                  "the medical centre."),
         ("4.7%", "<strong>Agriculture.</strong> Animal husbandry, crop farming and the cost of running the farms."),
         ("7.4%", "<strong>Running the organisation.</strong> Administration, bank charges and depreciation "
                  "&mdash; everything that is not a programme.")]
split = ""
for pct, what in SPLIT:
    split += ('      <div class="cost-row"><span class="cost-n">%s</span>'
              '<span class="cost-w">%s</span></div>\n' % (pct, what))

body += sec(head_block("Where it went", "Our 2025 accounts, audited.",
                       "For the year ended 31 December 2025, independently audited by Akomaye Adie &amp; Co., "
                       "Chartered Accountants, of Calabar. Of everything we spent, <strong>92.6% went to "
                       "programmes</strong>. Full statements are available to funders on request.")
            + '    <div class="costs">\n' + split + "    </div>\n",
            cls="grad-white-strong")

body += sec(head_block("Give once", "One-time gifts are being set up.",
                       "The previous site took one-time gifts through a WordPress plugin, which does not carry over "
                       "to the new site. A Stripe link for one-off and custom amounts is being arranged. In the "
                       "meantime, write to us and we will take it from there &mdash; including bank transfer, cheque, "
                       "and gifts from outside the United States.")
            + '    <div class="button-row">\n'
              '      <a class="button button--accent" href="mailto:info@corafrica.org.ng">info@corafrica.org.ng</a>\n'
              '      <a class="button button--plain" href="tel:+2349153142288">+234 915 314 2288</a>\n    </div>\n',
            cls="grad-paper-warm")

body += sec_wide('    <div class="panel">\n      <div class="grid grid--3">\n'
                 '        <div><h3 style="font-size:17px;margin-bottom:8px">Tax-deductible in the US</h3>'
                 '<p style="margin:0;font-size:14px;line-height:1.55;color:var(--ink-soft)">CORAfrica has held '
                 "<span class='nolig'>501(c)(3)</span> status in the United States since 2006. Gifts from US "
                 "taxpayers are tax-deductible. EIN [REQUEST FROM FR. PETER].</p></div>\n"
                 '        <div><h3 style="font-size:17px;margin-bottom:8px">Where it goes</h3>'
                 '<p style="margin:0;font-size:14px;line-height:1.55;color:var(--ink-soft)">In our audited 2025 '
                 "accounts, <strong>92.6% of everything we spent went to programmes</strong> &mdash; schools, "
                 "clinics, farms and loan funds &mdash; and 7.4% to running the organisation.</p></div>\n"
                 '        <div><h3 style="font-size:17px;margin-bottom:8px">Other ways to give</h3>'
                 '<p style="margin:0;font-size:14px;line-height:1.55;color:var(--ink-soft)">Fund a named project, '
                 "sponsor a classroom or a VASAC workshop, or partner with us as an institution. Write to "
                 '<a href="mailto:info@corafrica.org.ng">info@corafrica.org.ng</a>.</p></div>\n'
                 "      </div>\n    </div>\n", cls="bg-white", extra="section--flush-top section")

write("donate.html", head("donate.html", "Donate — CORAfrica",
      "Support education, healthcare and livelihoods for children in rural Nigeria. CORAfrica is a registered "
      "501(c)(3), so gifts from US donors are tax-deductible.")
      + BANNER + header("donate.html") + '<main id="main">\n' + body + "</main>\n" + FOOTER)


# ============================================================== contact
# Governance, per Fr. Peter's own docx — supplied 2026-08-31 and the NEWEST source
# we hold. The audited 2025 financial report lists a different board, but it states
# it as at 31 Dec 2025: an earlier snapshot, not a correction. See CONTENT-FACTS C5.
TRUSTEES = [("Michael Ana", "Chairman"), ("Cornelius Okochi", "Vice Chairman"), ("Mark Okpatuma", "Member"),
            ("Michael Abuo", "Member"), ("Pamela Enamhe", "Member"), ("James Bulem", "Member"),
            ("Ethan Suquet", "Member"), ("Adewale Ajayi", "Member / Secretary")]
ADMIN = [("Adewale Ajayi", "National Programmes Coordinator"), ("Elijah Ugani", "Projects Manager"),
         ("[FURTHER ROLES]", "To be confirmed")]


def person(name, role):
    return ('      <div class="person"><div class="person-name">%s</div>'
            '<div class="person-role">%s</div></div>\n' % (name, role))


body = ('<section class="page-hero-light grad-white-paper">\n  <div class="shell">\n'
        '    <p class="kicker">Contact us</p>\n'
        "    <h1>Talk to the people running the work.</h1>\n"
        '    <p class="lede">Our operations are directed from Ogoja, in Cross River State, and overseen by our Board '
        "of Trustees. For partnership, grant or press enquiries, write to us and we will route you to the right "
        "person.</p>\n  </div>\n</section>\n")
body += sec(head_block("Board of Trustees", "Governance.")
            + grid([person(n, r) for n, r in TRUSTEES], 4), cls="grad-paper-warm", extra="section--flush-top section")
body += sec(head_block("Administrative team", "Delivery.")
            + grid([person(n, r) for n, r in ADMIN], 4), cls="bg-white")
body += sec(head_block("Offices", "Where to find us.")
            + grid([card("Nigeria &mdash; operations", "No 48 Mbube Road, Opposite Govt. Technical College, Abakpa, Ogoja, Cross River State."),
                    card("Nigeria &mdash; headquarters", "Abuja. Our national office directs programmes across Cross River and Benue States."),
                    card("United States", "PO Box 13, Evans City, PA 16033. Our <span class='nolig'>501(c)(3)</span> entity and US board.")], 3)
            + '    <div class="button-row" style="margin-top:1.9rem">\n'
              '      <a class="button button--accent" href="mailto:info@corafrica.org.ng">info@corafrica.org.ng</a>\n'
              '      <a class="button button--plain" href="tel:+2349153142288">+234 915 314 2288</a>\n    </div>\n',
            cls="grad-white-strong")
write("contact.html", head("contact.html", "Contact Us — CORAfrica",
      "CORAfrica's Board of Trustees, administrative team, and offices in Ogoja, Abuja and Pennsylvania.")
      + BANNER + header("contact.html") + '<main id="main">\n' + body + "</main>\n" + FOOTER)


print("\nDonate links (recovered from the live page's markup, each opened to confirm):")
for amt, url in STRIPE_MONTHLY:
    print("  $%-6s monthly   %s" % (amt, url))
print("  %-15s %s" % ("one-time", STRIPE_ONE_TIME or "[STRIPE LINK NEEDED — GiveWP embed, does not carry over]"))
